package com.Baran.MineProtocol.regi;

import com.Baran.MineProtocol.item.*;
import com.Baran.MineProtocol.item.armor.ArmorKaihukuBoots;
import com.Baran.MineProtocol.item.armor.ArmorKaihukuChestPlate;
import com.Baran.MineProtocol.item.armor.ArmorKaihukuHelmet;
import com.Baran.MineProtocol.item.armor.ArmorKaihukuLeggings;
import com.Baran.MineProtocol.item.fish.*;
import com.Baran.MineProtocol.main.MineProtocol;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.Item;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.RegistryObject;

public class MineProtocolItems {

    public static final DeferredRegister<Item> ITEMS = DeferredRegister.create(ForgeRegistries.ITEMS, MineProtocol.MOD_ID);

    public static final RegistryObject<Item> TOKOYO = ITEMS.register("tokoyo", ItemTokoyo::new);
    public static final RegistryObject<Item> SUISYOU_GENSEKI = ITEMS.register("suisyou_genseki", ItemSuisyou_Genseki::new);
    public static final RegistryObject<Item> GROKENSEED = ITEMS.register("grokenseed", ItemGrokenSeed::new);
    public static final RegistryObject<Item> KANJYOUSEKI = ITEMS.register("kanjyouseki", ItemKanjyouseki::new);
    public static final RegistryObject<Item> ASTERIAINGOT = ITEMS.register("asteriaingot", ItemAsteriaIngot::new);
    public static final RegistryObject<Item> KAIHUKUINGOT = ITEMS.register("kaihukuingot", ItemKaihukuIngot::new);
    public static final RegistryObject<Item> SEWAYAKU_G1 = ITEMS.register("sewayaku_g1", ItemSewayakuG1::new);
    public static final RegistryObject<Item> SEWAYAKU_G2 = ITEMS.register("sewayaku_g2", ItemSewayakuG2::new);
    public static final RegistryObject<Item> SAZANAMI = ITEMS.register("sazanami", ItemSazanami::new);
    public static final RegistryObject<Item> BASECLAY = ITEMS.register("baseclay", ItemBaseClay::new);
    public static final RegistryObject<Item> DOUTEKI_KAKERA = ITEMS.register("douteki_kakera", ItemDoutekiKakera::new);
    public static final RegistryObject<Item> DOUTEKI_KESSYOU = ITEMS.register("douteki_kessyou", ItemDoutekiKessyou::new);
    public static final RegistryObject<Item> YAKUZAI_G1 = ITEMS.register("yakuzai_g1", ItemYakuzaiG1::new);
    public static final RegistryObject<Item> YAKUZAI_G2 = ITEMS.register("yakuzai_g2", ItemYakuzaiG2::new);
    public static final RegistryObject<Item> DORODORO_G1 = ITEMS.register("dorodoro_g1", ItemDorodoroG1::new);
    public static final RegistryObject<Item> DORODORO_G2 = ITEMS.register("dorodoro_g2", ItemDorodoroG2::new);
    public static final RegistryObject<Item> KAIHUKU_G1 = ITEMS.register("kaihuku_g1", ItemKaihuku_G1::new);
    public static final RegistryObject<Item> KAIHUKU_G2 = ITEMS.register("kaihuku_g2", ItemKaihuku_G2::new);
    public static final RegistryObject<Item> KAIHUKU_G3 = ITEMS.register("kaihuku_g3", ItemKaihuku_G3::new);
    public static final RegistryObject<Item> KAIHUKU_G4 = ITEMS.register("kaihuku_g4", ItemKaihuku_G4::new);
    public static final RegistryObject<Item> DRAGON_EDGE = ITEMS.register("doragon_edge",ItemDragonEdge::new);
    public static final RegistryObject<Item> DRAGON_AXE = ITEMS.register("dragon_axe",ItemDragonAxe::new);
    public static final RegistryObject<Item> DRAGON_PICKAXE = ITEMS.register("dragon_pickaxe",ItemDragonPickaxe::new);
    public static final RegistryObject<Item> DRAGON_SHOVEL = ITEMS.register("dragon_shovel",ItemDragonShovel::new);
    public static final RegistryObject<Item> DRAGON_HOE = ITEMS.register("dragon_hoe",ItemDragonHoe::new);
    public static final RegistryObject<Item> DRAGON_BOW = ITEMS.register("dragon_bow",ItemDragonBow::new);
    public static final RegistryObject<ArmorItem> KAIHUKU_HELMET = ITEMS.register("kaihuku_helmet", ArmorKaihukuHelmet::new);
    public static final RegistryObject<ArmorItem> KAIHUKU_CHESTPLATE = ITEMS.register("kaihuku_chestplate", ArmorKaihukuChestPlate::new);
    public static final RegistryObject<ArmorItem> KAIHUKU_LEGGINGS = ITEMS.register("kaihuku_leggings", ArmorKaihukuLeggings::new);
    public static final RegistryObject<ArmorItem> KAIHUKU_BOOTS = ITEMS.register("kaihuku_boots", ArmorKaihukuBoots::new);
    public static final RegistryObject<Item> AROMA_G1 = ITEMS.register("aroma_g1", ItemAroma_G1::new);
    public static final RegistryObject<Item> AROMA_G2 = ITEMS.register("aroma_g2", ItemAroma_G2::new);
    public static final RegistryObject<Item> AROMA_G3 = ITEMS.register("aroma_g3", ItemAroma_G3::new);
    public static final RegistryObject<Item> AROMA_G4 = ITEMS.register("aroma_g4", ItemAroma_G4::new);
    public static final RegistryObject<Item> KOUGEKI_SEIYU = ITEMS.register("kougeki_seiyu", ItemKougeki::new);
    public static final RegistryObject<Item> MAMORI_SEIYU = ITEMS.register("mamori_seiyu", ItemMamori::new);
    public static final RegistryObject<Item> ASTERIA_CHOCOLATE = ITEMS.register("asteria_chocolate", ItemAsteriaChocolate::new);
    public static final RegistryObject<Item> ASTERIA_CHOCOLATE_ULT = ITEMS.register("asteria_chocolate_ult", ItemAsteriaChocolateULT::new);
    public static final RegistryObject<Item> ASTERIA_CHOCOLATE_B = ITEMS.register("asteria_chocolate_b", ItemAsteriaChocolateB::new);
    public static final RegistryObject<Item> KOAZI = ITEMS.register("koazi", FishKoAzi::new);
    public static final RegistryObject<Item> MAAZI = ITEMS.register("maazi", FishMaAzi::new);
    public static final RegistryObject<Item> SUZUME = ITEMS.register("suzume", FishSuzume::new);
    public static final RegistryObject<Item> OOSUZUME = ITEMS.register("oosuzume", FishOoSuzume::new);
    public static final RegistryObject<Item> KUJYAKU = ITEMS.register("kujyaku", FishKujyaku::new);
    public static final RegistryObject<Item> OOKUJYAKU = ITEMS.register("ookujyaku", FishOoKujyaku::new);
    public static final RegistryObject<Item> HUGU = ITEMS.register("hugu", FishHugu::new);
    public static final RegistryObject<Item> OOHUGU = ITEMS.register("oohugu", FishOoHugu::new);
    public static final RegistryObject<Item> ANKOU = ITEMS.register("ankou", FishAnkou::new);
    public static final RegistryObject<Item> OOANKOU = ITEMS.register("ooankou", FishOoAnkou::new);
    public static final RegistryObject<Item> KATUO = ITEMS.register("katuo", FishKatuo::new);
    public static final RegistryObject<Item> OOKATUO = ITEMS.register("ookatuo", FishOoKatuo::new);
    public static final RegistryObject<Item> TUNA = ITEMS.register("tuna", FishTuna::new);
    public static final RegistryObject<Item> OOTUNA = ITEMS.register("ootuna", FishOoTuna::new);
    public static final RegistryObject<Item> COOKED_KOAZI = ITEMS.register("cooked_koazi", CookedKoAzi::new);
    public static final RegistryObject<Item> COOKED_MAAZI = ITEMS.register("cooked_maazi", CookedMaAzi::new);
    public static final RegistryObject<Item> COOKED_SUZUME = ITEMS.register("cooked_suzume", CookedSuzume::new);
    public static final RegistryObject<Item> COOKED_OOSUZUME = ITEMS.register("cooked_oosuzume", CookedOoSuzume::new);
    public static final RegistryObject<Item> COOKED_KUJYAKU = ITEMS.register("cooked_kujyaku", CookedKujyaku::new);
    public static final RegistryObject<Item> COOKED_OOKUJYAKU = ITEMS.register("cooked_ookujyaku", CookedOoKujyaku::new);
    public static final RegistryObject<Item> COOKED_HUGU = ITEMS.register("cooked_hugu", CookedHugu::new);
    public static final RegistryObject<Item> COOKED_OOHUGU = ITEMS.register("cooked_oohugu", CookedOoHugu::new);
    public static final RegistryObject<Item> COOKED_ANKOU = ITEMS.register("cooked_ankou", CookedAnkou::new);
    public static final RegistryObject<Item> COOKED_OOANKOU = ITEMS.register("cooked_ooankou", CookedOoAnkou::new);
    public static final RegistryObject<Item> COOKED_KATUO = ITEMS.register("cooked_katuo", CookedKatuo::new);
    public static final RegistryObject<Item> COOKED_OOKATUO = ITEMS.register("cooked_ookatuo", CookedOoKatuo::new);
    public static final RegistryObject<Item> COOKED_TUNA = ITEMS.register("cooked_tuna", CookedTuna::new);
    public static final RegistryObject<Item> COOKED_OOTUNA = ITEMS.register("cooked_ootuna", CookedOoTuna::new);
    public static final RegistryObject<Item> GC = ITEMS.register("gc", ItemGC::new);
    public static final RegistryObject<Item> ROSE = ITEMS.register("rose", ItemRose::new);
    public static final RegistryObject<Item> BPP = ITEMS.register("bpp", ItemBPP::new);
    public static final RegistryObject<Item> FISH_STICK = ITEMS.register("fish_stick", FishStick::new);
    public static final RegistryObject<Item> MAAZI_EDGE = ITEMS.register("maazi_edge", FishMaAziEdge::new);
    public static final RegistryObject<Item> SUZUME_EDGE = ITEMS.register("suzume_edge", FishSuzumeEdge::new);
    public static final RegistryObject<Item> KUJYAKU_EDGE = ITEMS.register("kujyaku_edge", FishKujyakuEdge::new);
    public static final RegistryObject<Item> HUGU_EDGE = ITEMS.register("hugu_edge", FishHuguEdge::new);
    public static final RegistryObject<Item> ANKOU_EDGE = ITEMS.register("ankou_edge", FishAnkouEdge::new);
    public static final RegistryObject<Item> KATUO_EDGE = ITEMS.register("katuo_edge", FishKatuoEdge::new);
    public static final RegistryObject<Item> TUNA_EDGE = ITEMS.register("tuna_edge", FishTunaEdge::new);
    public static final RegistryObject<Item> TORANOMAKI_G1 = ITEMS.register("toranomaki_g1", () -> new ItemToranomakiG1(new Item.Properties()));
    public static final RegistryObject<Item> TORANOMAKI_G3 = ITEMS.register("toranomaki_g3", () -> new ItemToranomakiG3(new Item.Properties()));
    public static final RegistryObject<Item> MAGUNIA = ITEMS.register("magunia", ItemMagunia::new);
    public static final RegistryObject<Item> TAIRAI = ITEMS.register("tairai", ItemTairai::new);

}
