package com.Baran.MineProtocol.regi.tab;

import com.Baran.MineProtocol.regi.MineProtocolBlocks;
import com.Baran.MineProtocol.regi.MineProtocolItems;
import net.minecraft.world.item.Item;

public class MineProMain {

    public static final Item[] items = {

            MineProtocolItems.TOKOYO.get(),
            MineProtocolItems.SUISYOU_GENSEKI.get(),
            MineProtocolItems.GROKENSEED.get(),
            MineProtocolItems.KANJYOUSEKI.get(),
            MineProtocolItems.SAZANAMI.get(),
            MineProtocolItems.BASECLAY.get(),
            MineProtocolItems.SEWAYAKU_G1.get(),
            MineProtocolItems.SEWAYAKU_G2.get(),
            MineProtocolItems.YAKUZAI_G1.get(),
            MineProtocolItems.YAKUZAI_G2.get(),
            MineProtocolItems.DOUTEKI_KAKERA.get(),
            MineProtocolItems.DOUTEKI_KESSYOU.get(),
            MineProtocolItems.DORODORO_G1.get(),
            MineProtocolItems.DORODORO_G2.get(),
            MineProtocolItems.KOUGEKI_SEIYU.get(),
            MineProtocolItems.MAMORI_SEIYU.get(),
            MineProtocolItems.ASTERIA_CHOCOLATE.get(),
            MineProtocolItems.ASTERIA_CHOCOLATE_ULT.get(),
            MineProtocolItems.ASTERIA_CHOCOLATE_B.get(),
            MineProtocolBlocks.BlockItems.ASTERIA_ORE_ITEM.get(),
            MineProtocolBlocks.BlockItems.KAIHUKU_ORE_ITEM.get(),
            MineProtocolBlocks.BlockItems.ASTERIA_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.KAIHUKU_BLOCK_ITEM.get(),
            MineProtocolItems.ASTERIAINGOT.get(),
            MineProtocolItems.KAIHUKUINGOT.get(),
            MineProtocolItems.DRAGON_EDGE.get(),
            MineProtocolItems.DRAGON_AXE.get(),
            MineProtocolItems.DRAGON_PICKAXE.get(),
            MineProtocolItems.DRAGON_SHOVEL.get(),
            MineProtocolItems.DRAGON_HOE.get(),
            MineProtocolItems.DRAGON_BOW.get(),
            MineProtocolItems.KAIHUKU_HELMET.get(),
            MineProtocolItems.KAIHUKU_CHESTPLATE.get(),
            MineProtocolItems.KAIHUKU_LEGGINGS.get(),
            MineProtocolItems.KAIHUKU_BOOTS.get(),
            MineProtocolItems.KAIHUKU_G1.get(),
            MineProtocolItems.KAIHUKU_G2.get(),
            MineProtocolItems.KAIHUKU_G3.get(),
            MineProtocolItems.KAIHUKU_G4.get(),
            MineProtocolItems.AROMA_G1.get(),
            MineProtocolItems.AROMA_G2.get(),
            MineProtocolItems.AROMA_G3.get(),
            MineProtocolItems.AROMA_G4.get(),
            MineProtocolItems.GC.get(),
            MineProtocolItems.ROSE.get(),
            MineProtocolItems.BPP.get(),
            MineProtocolItems.TORANOMAKI_G1.get(),
            MineProtocolItems.TORANOMAKI_G3.get(),
            MineProtocolBlocks.BlockItems.ITYAN_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.GOBU_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.RED_GOBU_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.YELLOW_GOBU_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.NAPPO_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.RED_NAPPO_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.GREEN_NAPPO_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.GOLD_NAPPO_BLOCK_ITEM.get(),
            MineProtocolBlocks.BlockItems.SILVER_NAPPO_BLOCK_ITEM.get(),
            MineProtocolItems.FISH_STICK.get(),
            MineProtocolItems.KOAZI.get(),
            MineProtocolItems.MAAZI.get(),
            MineProtocolItems.SUZUME.get(),
            MineProtocolItems.OOSUZUME.get(),
            MineProtocolItems.KUJYAKU.get(),
            MineProtocolItems.OOKUJYAKU.get(),
            MineProtocolItems.HUGU.get(),
            MineProtocolItems.OOHUGU.get(),
            MineProtocolItems.ANKOU.get(),
            MineProtocolItems.OOANKOU.get(),
            MineProtocolItems.KATUO.get(),
            MineProtocolItems.OOKATUO.get(),
            //MineProtocolItems.TUNA.get(),
            //MineProtocolItems.OOTUNA.get(),
            MineProtocolItems.COOKED_KOAZI.get(),
            MineProtocolItems.COOKED_MAAZI.get(),
            MineProtocolItems.COOKED_SUZUME.get(),
            MineProtocolItems.COOKED_OOSUZUME.get(),
            MineProtocolItems.COOKED_KUJYAKU.get(),
            MineProtocolItems.COOKED_OOKUJYAKU.get(),
            MineProtocolItems.COOKED_HUGU.get(),
            MineProtocolItems.COOKED_OOHUGU.get(),
            MineProtocolItems.COOKED_ANKOU.get(),
            MineProtocolItems.COOKED_OOANKOU.get(),
            MineProtocolItems.COOKED_KATUO.get(),
            MineProtocolItems.COOKED_OOKATUO.get(),
            //MineProtocolItems.COOKED_TUNA.get(),
            //MineProtocolItems.COOKED_OOTUNA.get(),
            MineProtocolItems.MAAZI_EDGE.get(),
            MineProtocolItems.SUZUME_EDGE.get(),
            MineProtocolItems.KUJYAKU_EDGE.get(),
            MineProtocolItems.HUGU_EDGE.get(),
            MineProtocolItems.ANKOU_EDGE.get(),
            MineProtocolItems.KATUO_EDGE.get(),
            //MineProtocolItems.TUNA_EDGE.get(),

    };
}
